spring:
  application:
    name: google-course-tools
  profiles:
    active: redis
  session:
    store-type: none
  output:
    ansi:
      enabled: ALWAYS
gct:
  impersonationAccount: gctadmin@iu.edu
  domain: iu.edu
  version: ${app.version}
  rootFolderId: 1uMDMc-7FKRy7t3YK1y-jk6a7u3HvmP_V
  coursesFolderId: 1NN_LGT_1Kdw6ywsMpZ-7PD1mPLQrfD2s
  usersFolderId: 1ZreeUlo-AnvLEBlpMmsmOJ9MueJSg_sS

---

spring:
  profiles: redis
  session:
    store-type: redis